In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/strava-activities/activities.csv
/kaggle/input/strava-activities/activities(1).csv
/kaggle/input/strava-activities/activities copy 6.csv
/kaggle/input/strava-activities/activities copy 3.csv
/kaggle/input/strava-activities/activities copy.csv
/kaggle/input/strava-activities/activities (1).csv
/kaggle/input/strava-activities/activities copy 10.csv
/kaggle/input/strava-activities/activities (5).csv
/kaggle/input/strava-activities/activities copy 7.csv
/kaggle/input/strava-activities/activities (2).csv
/kaggle/input/strava-activities/activities (4).csv
/kaggle/input/strava-activities/activities copy 2.csv
/kaggle/input/strava-activities/activities copy 5.csv
/kaggle/input/strava-activities/activities copy 9.csv
/kaggle/input/strava-activities/activities copy 4.csv
/kaggle/input/strava-activities/activities (3).csv
/kaggle/input/strava-activities/activities (1) copy.csv
/kaggle/input/strava-activities/activities copy 11.csv
/kaggle/input/activities-garmin/Activities Lukasz.csv
/kaggle/input/activities-garmin/Activities Jola.csv

# Strava part

In [2]:
df_strava = pd.read_csv('/kaggle/input/strava-activities/activities.csv') 
df_strava.columns

Index(['Activity ID', 'Activity Date', 'Activity Name', 'Activity Type',
       'Activity Description', 'Elapsed Time', 'Distance', 'Max Heart Rate',
       'Relative Effort', 'Commute', 'Activity Private Note', 'Activity Gear',
       'Filename', 'Athlete Weight', 'Bike Weight', 'Elapsed Time.1',
       'Moving Time', 'Distance.1', 'Max Speed', 'Average Speed',
       'Elevation Gain', 'Elevation Loss', 'Elevation Low', 'Elevation High',
       'Max Grade', 'Average Grade', 'Average Positive Grade',
       'Average Negative Grade', 'Max Cadence', 'Average Cadence',
       'Max Heart Rate.1', 'Average Heart Rate', 'Max Watts', 'Average Watts',
       'Calories', 'Max Temperature', 'Average Temperature',
       'Relative Effort.1', 'Total Work', 'Number of Runs', 'Uphill Time',
       'Downhill Time', 'Other Time', 'Perceived Exertion', 'Type',
       'Start Time', 'Weighted Average Power', 'Power Count',
       'Prefer Perceived Exertion', 'Perceived Relative Effort', 'Commute.1',
       'Total Weight Lifted', 'From Upload', 'Grade Adjusted Distance',
       'Weather Observation Time', 'Weather Condition', 'Weather Temperature',
       'Apparent Temperature', 'Dewpoint', 'Humidity', 'Weather Pressure',
       'Wind Speed', 'Wind Gust', 'Wind Bearing', 'Precipitation Intensity',
       'Sunrise Time', 'Sunset Time', 'Moon Phase', 'Bike', 'Gear',
       'Precipitation Probability', 'Precipitation Type', 'Cloud Cover',
       'Weather Visibility', 'UV Index', 'Weather Ozone', 'Jump Count',
       'Total Grit', 'Average Flow', 'Flagged', 'Average Elapsed Speed',
       'Dirt Distance', 'Newly Explored Distance',
       'Newly Explored Dirt Distance', 'Activity Count', 'Total Steps',
       'Carbon Saved', 'Pool Length', 'Training Load', 'Intensity',
       'Average Grade Adjusted Pace', 'Timer Time', 'Total Cycles', 'Recovery',
       'With Pet', 'Competition', 'Long Run', 'For a Cause', 'Media'],
      dtype='object')

In [3]:
from dateutil import parser

def parse_mixed_date(s):
    try:
        return parser.parse(s, dayfirst=False)
    except Exception:
        print(s)
        return pd.NaT

## Loading Strava datasets with columns formatting

In [4]:
import glob 

path = "/kaggle/input/strava-activities/"
files = glob.glob(os.path.join(path, "*.csv"))

columns_to_keep = [
    'Activity ID', 'Activity Date', 'Activity Type',
    'Elapsed Time', 'Distance', 'Max Heart Rate', 'Average Heart Rate',
    'Relative Effort', 'Athlete Weight',
    'Moving Time', 'Max Speed', 'Average Speed',
    'Elevation Gain', 'Elevation Loss', 'Average Temperature'
]

dfs = []

for i, f in enumerate(files):
    df_temp = pd.read_csv(f, usecols=lambda c: c in columns_to_keep, low_memory=False)
    df_temp = df_temp.replace(["--", "", "None"], np.nan)
    df_temp["athlete"] = f"athlete_{i+1}"
    df_temp["Activity Date"] = df_temp["Activity Date"].apply(parse_mixed_date)
    df_temp['Max Heart Rate'] = pd.to_numeric(df_temp['Max Heart Rate'], errors='coerce').astype(float)
    df_temp['Average Heart Rate'] = pd.to_numeric(df_temp['Average Heart Rate'], errors='coerce').astype(float)
    df_temp['Moving Time'] = pd.to_numeric(df_temp['Moving Time'], errors='coerce').astype(int)
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)
print(f"Loaded {len(dfs)} athletes, total records: {len(df)}")

df

Loaded 18 athletes, total records: 17499

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Activity ID,Activity Date,Activity Type,Elapsed Time,Distance,Max Heart Rate,Relative Effort,Athlete Weight,Moving Time,Max Speed,Average Speed,Elevation Gain,Elevation Loss,Average Heart Rate,Average Temperature,athlete
0,5642776701,2021-07-17 15:01:35,Ride,5632,46.29,NaN,NaN,NaN,5162,18.400,8.967,194.7,194.7,NaN,NaN,athlete_1
1,5646537801,2021-07-18 09:58:13,Ride,4195,34.99,NaN,NaN,NaN,4040,12.900,8.661,89.1,89.0,NaN,NaN,athlete_1
2,5648599204,2021-07-18 15:15:15,Ride,5718,45.81,NaN,NaN,NaN,5062,16.600,9.051,194.7,194.9,NaN,NaN,athlete_1
3,5675423119,2021-07-23 16:59:42,Ride,5492,34.03,NaN,NaN,NaN,4052,18.600,8.400,241.1,241.1,NaN,NaN,athlete_1
4,5683066237,2021-07-25 07:46:00,Ride,3529,30.96,NaN,NaN,NaN,3529,15.500,8.773,204.2,204.0,NaN,NaN,athlete_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17494,16117749305,2025-10-12 07:30:14,Ride,23150,28.47,NaN,NaN,NaN,7347,10.851,3.876,89.6,89.6,NaN,NaN,athlete_18
17495,16121717679,2025-10-12 03:05:14,Hike,6213,9.64,NaN,NaN,NaN,5687,3.010,1.697,251.4,286.3,NaN,NaN,athlete_18
17496,16160559110,2025-10-16 14:40:13,Run,1658,5.21,NaN,NaN,NaN,1658,5.200,3.146,3.7,5.5,NaN,NaN,athlete_18
17497,16190304575,2025-10-19 08:00:11,Run,12400,42.36,190.0,458.0,NaN,12327,4.480,3.437,137.0,130.0,175.0,NaN,athlete_18
17498,16250286229,2025-10-25 08:40:19,Ride,9565,55.65,NaN,NaN,NaN,7582,14.990,7.341,375.0,382.0,NaN,11.0,athlete_18

## Checking Null values and dropping less valuable columns

In [5]:
cols_to_check = ['Average Temperature', 'Athlete Weight', 'Relative Effort', 'Average Heart Rate']

for col in cols_to_check:
    n_nan = df[col].isna().sum()
    pct_nan = df[col].isna().mean() * 100
    print(f"Missing values in '{col}': {n_nan} ({pct_nan:.2f}%)")

Missing values in 'Average Temperature': 9854 (56.31%)
Missing values in 'Athlete Weight': 16984 (97.06%)
Missing values in 'Relative Effort': 7344 (41.97%)
Missing values in 'Average Heart Rate': 7141 (40.81%)

In [6]:
df = df.drop(['Athlete Weight', 'Activity ID', 'Relative Effort'], axis=1)

# Garmin part

## Functions to parse particular columns

In [7]:
def fix_temperature(df_temp):
    # Średnia temperatura z max i min
    if {'Max Temperature', 'Min Temperature'}.issubset(df_temp.columns):
        # Konwersja z przecinków na kropki, błędne wartości -> NaN
        for col in ['Max Temperature', 'Min Temperature']:
            df_temp[col] = (
                df_temp[col]
                .astype(str)
                .str.replace(',', '.', regex=False)
                .replace(['', 'nan', 'None'], np.nan)
                .astype(float)
            )        
        # Oblicz średnią tylko gdy coś istnieje
        valid = df_temp[['Max Temperature', 'Min Temperature']].notna().any(axis=1)
        df_temp.loc[valid, 'Average Temperature'] = df_temp[['Max Temperature', 'Min Temperature']].mean(axis=1)
        df_temp.drop(['Max Temperature', 'Min Temperature'], axis=1, inplace=True)
    else:
        print("Missing 'Max Temperature' or 'Min Temperature' columns")
    return df_temp

def parse_avg_speed(row):
    val = row.get("Average Speed")
    typ = row.get("Activity Type")
    
    # Brakujace wartości i '--'
    if val in [None, "", "--"] or pd.isna(val):
        return np.nan
    
    val = str(val).replace(",", ".")
    
    try:
        # Kolarskwo: już w km/h
        if typ == "Ride":
            kmh = float(val)
        
        # Bieganie: min/km → km/h
        elif typ == "Run":
            if ":" in val:
                mins, secs = map(float, val.split(":"))
            else:
                mins = float(val)
                secs = 0
            pace_min_per_km = mins + secs/60
            kmh = 60 / pace_min_per_km
        
        # Pływanie: min/100m → km/h
        elif typ == "Swim":
            if ":" in val:
                mins, secs = map(float, val.split(":"))
            else:
                mins = float(val)
                secs = 0
            pace_min_per_100m = mins + secs/60
            kmh = 60 / pace_min_per_100m * 10
        
        # Inne aktywności -> NaN bo niepotrzebne
        else:
            return np.nan
        
        # Zamień km/h → m/s
        return kmh * 1000 / 3600
    
    except:
        return np.nan


def fix_swim(df_garmin):
    
    df_garmin["Distance"] = pd.to_numeric(df_garmin["Distance"], errors="coerce")
    
    # Jeśli dystans za duży (podany w metrach) zmiana jednostki 
    mask_swim_fix = (df_garmin["Activity Type"] == "Swim") & (df_garmin["Distance"] > 15)
    df_garmin.loc[mask_swim_fix, "Distance"] = df_garmin.loc[mask_swim_fix, "Distance"] / 1000
    
    print(f"Fixed {mask_swim_fix.sum()} swim distances bigger than 15 (converted to km)")
    return df_garmin

## Units alignment between datasets

In [8]:
path = "/kaggle/input/activities-garmin/"
files = glob.glob(os.path.join(path, "*.csv"))

column_map = {
    'Typ aktywności': 'Activity Type',
    'Data': 'Activity Date',
    'Dystans': 'Distance',                 
    'Czas': 'Elapsed Time',
    'Czas ruchu': 'Moving Time',
    'Maksymalne tętno': 'Max Heart Rate',
    'Średnie tętno': 'Average Heart Rate',
    'Całkowity wznios': 'Elevation Gain',
    'Całkowity spadek': 'Elevation Loss',
    'Maksymalna prędkość': 'Max Speed',
    'Średnia prędkość': 'Average Speed',
    'Maksymalna temperatura': 'Max Temperature',
    'Minimalna temperatura': 'Min Temperature',
    'Średnie tempo':'Average Speed',
    'Najlepsze tempo': 'Max Speed'
}

activity_map = {
    'Bieganie': 'Run',
    'Bieg na bieżni': 'Run',
    'Kolarstwo': 'Ride',
    'Kolarstwo szosowe': 'Ride',
    'Jazda na rowerze treningowym': 'Ride',
    'Jazda po drodze szutrowej/nieutwardzonej': 'Ride',
    'Pływanie na basenie': 'Swim',
    'Pływanie open water': 'Swim',
    'Trening siłowy': 'Weight Training',
    'Virtual Run': 'Run',
    'Virtual Ride': 'Ride',
    'Run':'Run',
    'Ride': 'Ride',
    'Swim': 'Swim',
    'Weight Training':'Weight Training'
}


columns_to_keep = list(column_map.keys())

dfs = []

for i, f in enumerate(files):
    df_temp = pd.read_csv(f, usecols=lambda c: c in columns_to_keep, low_memory=False)
    df_temp = df_temp.rename(columns=column_map)

    # Średnia temperatura z max i min
    df_temp = fix_temperature(df_temp)

    # Czas: HH:MM:SS → sekundy
    for col in ["Elapsed Time", "Moving Time"]:
        if df_temp[col].dtype == "object":
            df_temp[col] = pd.to_timedelta(df_temp[col], errors="coerce").dt.total_seconds().astype(int)

    df_temp = df_temp.replace("--", np.nan)

    df_temp['Activity Type'] = df_temp['Activity Type'].map(activity_map).fillna('Workout')
    
    # Data
    df_temp["Activity Date"] = pd.to_datetime(df_temp["Activity Date"], errors="coerce")

    df_temp["Elevation Gain"] = df_temp["Elevation Gain"].astype(float)
    df_temp["Elevation Loss"] = df_temp["Elevation Loss"].astype(float)

    #distance
    df_temp["Distance"] = df_temp["Distance"].astype(str).str.replace(',', '.', regex=False).replace(['', 'nan', 'None'], np.nan).astype(float)
    df_temp = fix_swim(df_temp)

    df_temp["Average Speed"] = df_temp["Average Speed"].astype(str)
    df_temp["Average Speed"] = df_temp.apply(parse_avg_speed, axis=1)

    df_temp["Max Speed"] = df_temp["Max Speed"].astype(str)
    df_temp["Max Speed"] = df_temp.apply(parse_avg_speed, axis=1)

    df_temp['Max Heart Rate'] = df_temp['Max Heart Rate'].astype(float)
    df_temp['Average Heart Rate'] = df_temp['Average Heart Rate'].astype(float)
    df_temp['Average Heart Rate'] = df_temp['Average Heart Rate'].astype(float)  
    
    df_temp["athlete"] = f"athlete_garmin_{i+1}"  
    
    dfs.append(df_temp)

df_garmin = pd.concat(dfs, ignore_index=True)

print(f"Loaded {len(dfs)} Garmin athletes, total records: {len(df_garmin)}")

df_garmin.head()

Fixed 30 swim distances bigger than 15 (converted to km)
Fixed 11 swim distances bigger than 15 (converted to km)
Loaded 2 Garmin athletes, total records: 720

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Activity Type,Activity Date,Distance,Elapsed Time,Average Heart Rate,Max Heart Rate,Average Speed,Max Speed,Elevation Gain,Elevation Loss,Moving Time,Average Temperature,athlete
0,Weight Training,2025-10-03 18:55:15,0.00,5375,94.0,145.0,NaN,NaN,NaN,NaN,1314,29.5,athlete_garmin_1
1,Weight Training,2025-09-30 17:50:39,0.00,4118,84.0,147.0,NaN,NaN,NaN,NaN,1630,29.5,athlete_garmin_1
2,Workout,2025-09-28 16:57:28,3.04,3583,104.0,127.0,NaN,NaN,26.0,182.0,2878,28.0,athlete_garmin_1
3,Ride,2025-09-27 08:46:39,28.01,4691,NaN,NaN,5.972222,1.658951,117.0,116.0,4680,13.5,athlete_garmin_1
4,Run,2025-09-15 15:12:02,7.50,3095,132.0,146.0,2.427184,6.866667,13.0,12.0,3022,25.5,athlete_garmin_1

In [9]:
df['Activity Type'] = df['Activity Type'].map(activity_map).fillna('Workout')
print(df[df['Activity Type'] == 'Swim']['Distance'].max())
df["Distance"] = df["Distance"].astype(str).str.replace(',', '.', regex=False).replace(['', 'nan', 'None'], np.nan).astype(float)
df = fix_swim(df)
print(df[df['Activity Type'] == 'Swim']['Distance'].max())

print(df_garmin['Activity Type'].unique())
print(df['Activity Type'].unique())

df_garmin.head()

995
Fixed 314 swim distances bigger than 15 (converted to km)
8.5
['Weight Training' 'Workout' 'Ride' 'Run' 'Swim']
['Ride' 'Workout' 'Run' 'Swim' 'Weight Training']

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Activity Type,Activity Date,Distance,Elapsed Time,Average Heart Rate,Max Heart Rate,Average Speed,Max Speed,Elevation Gain,Elevation Loss,Moving Time,Average Temperature,athlete
0,Weight Training,2025-10-03 18:55:15,0.00,5375,94.0,145.0,NaN,NaN,NaN,NaN,1314,29.5,athlete_garmin_1
1,Weight Training,2025-09-30 17:50:39,0.00,4118,84.0,147.0,NaN,NaN,NaN,NaN,1630,29.5,athlete_garmin_1
2,Workout,2025-09-28 16:57:28,3.04,3583,104.0,127.0,NaN,NaN,26.0,182.0,2878,28.0,athlete_garmin_1
3,Ride,2025-09-27 08:46:39,28.01,4691,NaN,NaN,5.972222,1.658951,117.0,116.0,4680,13.5,athlete_garmin_1
4,Run,2025-09-15 15:12:02,7.50,3095,132.0,146.0,2.427184,6.866667,13.0,12.0,3022,25.5,athlete_garmin_1

In [10]:
df_garmin.describe()

,Activity Date,Distance,Elapsed Time,Average Heart Rate,Max Heart Rate,Average Speed,Max Speed,Elevation Gain,Elevation Loss,Moving Time,Average Temperature
count,720,720.000000,720.000000,511.000000,511.000000,598.000000,598.000000,496.000000,498.000000,720.000000,720.000000
mean,2025-04-21 19:25:41.059722240,11.007786,3346.913889,120.849315,148.244618,9.578764,4.320675,97.213710,97.323293,2722.537500,23.939583
min,2024-09-20 16:59:31,0.000000,11.000000,63.000000,70.000000,0.371058,0.717593,1.000000,3.000000,0.000000,5.500000
25%,2025-02-24 17:32:47,1.387500,1114.250000,110.000000,137.000000,2.710027,1.658951,25.500000,28.000000,1001.750000,21.000000
50%,2025-04-27 16:03:37,8.040000,3653.000000,125.000000,149.000000,4.958333,3.175000,65.500000,59.000000,2761.000000,24.500000
75%,2025-06-19 18:56:29,21.360000,4110.250000,136.500000,163.000000,6.166667,6.216667,160.250000,144.000000,3886.500000,28.000000
max,2025-10-03 18:55:15,72.500000,126965.000000,164.000000,195.000000,83.333333,49.016667,834.000000,832.000000,16116.000000,34.000000
std,NaN,11.612914,5050.263092,24.069483,20.544281,15.369188,4.319785,106.198702,111.793023,1849.855549,4.854507

# Merging datasets

In [11]:
df_final = pd.concat([df, df_garmin], ignore_index=True)
df_final['Distance'] = df_final['Distance'] * 1000

condition = (
    (df_final['Activity Type'] == 'Run') &
    ((df_final['Average Speed'] > 8) | (df_final['Max Speed'] > 15) | (df_final['Distance'] < 1000))
)

dropped = condition.sum()
df_final = df_final[~condition]

print(f"Dropped {dropped} running activities with unrealistic speeds or too short distance.")

df_final[df_final['Activity Type'] == 'Run'].describe()

Dropped 431 running activities with unrealistic speeds or too short distance.

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)

,Activity Date,Elapsed Time,Distance,Max Heart Rate,Moving Time,Max Speed,Average Speed,Elevation Gain,Elevation Loss,Average Heart Rate,Average Temperature
count,5959,5959.00000,5959.000000,3618.000000,5959.000000,5912.000000,5927.000000,5917.000000,5861.000000,3616.000000,2220.000000
mean,2023-12-04 14:18:51.882698240,3494.29317,8119.021648,174.656993,2582.206578,5.538028,3.229774,53.064594,89.693158,153.688606,21.649099
min,2008-08-24 10:02:49,156.00000,1000.000000,85.000000,156.000000,1.492000,0.686000,0.000000,-2.500000,79.000000,2.000000
25%,2023-03-02 16:32:54,1530.00000,4600.000000,163.250000,1423.000000,4.438000,2.899000,10.000000,16.000000,145.000000,18.000000
50%,2024-05-28 14:33:47,2717.00000,7830.000000,177.000000,2447.000000,5.287000,3.208000,26.000000,38.000000,153.000000,22.000000
75%,2025-02-27 23:41:36,3911.50000,10800.000000,187.000000,3492.500000,6.333000,3.528000,58.000000,102.000000,162.000000,26.000000
max,2025-10-19 08:00:11,971495.00000,42790.000000,244.000000,16353.000000,14.950000,6.645000,1463.200000,12483.000000,201.000000,36.000000
std,NaN,21014.75683,4775.427494,16.525258,1567.527264,1.583664,0.574783,95.206042,263.663433,14.517632,5.555555

## Finding max HR for each athlete

In [12]:
def validate_hr_data(df):
    # Usuwamy fizycznie niemożliwe wartości tętna 
    hr_mask = (df['Average Heart Rate'] >= 40) & (df['Average Heart Rate'] <= 220)
    return df[hr_mask]

df_final = validate_hr_data(df_final)
max_hr_per_athlete = df_final.groupby("athlete")["Max Heart Rate"].max()
print(max_hr_per_athlete)

athlete
athlete_1           222.0
athlete_11          220.0
athlete_12          253.0
athlete_13          205.0
athlete_14          190.0
athlete_15          230.0
athlete_16          220.0
athlete_17          189.0
athlete_18          240.0
athlete_2           244.0
athlete_3           190.0
athlete_4           204.0
athlete_5           210.0
athlete_7           201.0
athlete_8           207.0
athlete_9           192.0
athlete_garmin_1    195.0
athlete_garmin_2    195.0
Name: Max Heart Rate, dtype: float64

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

In [13]:
# Usuń zawodników, którzy nie mają żadnych danych o tętnie
def remove_athletes_without_hr(df):
    athletes_to_remove = (
        df.groupby("athlete")[["Max Heart Rate", "Average Heart Rate"]]
        .apply(lambda x: x.isna().all().all())
    )
    athletes_to_remove = athletes_to_remove[athletes_to_remove].index.tolist()

    if athletes_to_remove:
        print(f"Usuwam zawodników bez danych o tętnie: {athletes_to_remove}")
        df = df[~df["athlete"].isin(athletes_to_remove)]
    else:
        print("Wszyscy zawodnicy mają dane o tętnie")
    return df


# Użycie po scaleniu wszystkich danych
df_final = remove_athletes_without_hr(df_final)

Wszyscy zawodnicy mają dane o tętnie

In [14]:
# Filtrujemy aktywności biegowe/rowerowe
df_no_swim = df_final[df_final["Activity Type"].isin(['Ride', 'Run'])]

# Grupujemy po sportowcu i wybieramy 10 najwyższe max_hr
top10_avg_hr = (
    df_no_swim.sort_values(["athlete", "Max Heart Rate"], ascending=[True, False])
    .groupby("athlete")["Max Heart Rate"]
    .apply(lambda x: x.head(10).mean())  # średnia z 10 najwyższych
)

# Konwersja do słownika
max_hr_dict = top10_avg_hr.to_dict()
print(max_hr_dict)

{'athlete_1': 204.1, 'athlete_11': 200.1, 'athlete_12': 210.0, 'athlete_13': 200.4, 'athlete_14': 186.5, 'athlete_15': 216.2, 'athlete_16': 200.1, 'athlete_17': 178.1, 'athlete_18': 227.0, 'athlete_2': 207.1, 'athlete_3': 188.1, 'athlete_4': 196.5, 'athlete_5': 197.2, 'athlete_7': 195.3, 'athlete_8': 199.1, 'athlete_9': 190.4, 'athlete_garmin_1': 183.9, 'athlete_garmin_2': 185.7}

## Handle missing values

In [15]:
# Sprawdzenie missing values 
missing = df_final.isnull().sum()
print("Missing values before imputation:\n", missing)

# Kolumny numeryczne: wypełnij mediana dla sportowca
numeric_cols = df_final.select_dtypes(include='number').columns

activity_medians = (
    df_final.groupby("Activity Type")[numeric_cols]
    .median()
    .to_dict(orient="index")
)

def fill_missing_by_group(x):
    activity = x.name[1]  # grupowanie po (athlete, Activity Type)
    x_filled = x.fillna(x.median())  # per-athlete+activity mediana
    # medaina per-activity jeśli nadal NaN
    for col in numeric_cols:
        if x_filled[col].isna().any():
            fallback_val = activity_medians.get(activity, {}).get(col, np.nan)
            x_filled[col] = x_filled[col].fillna(fallback_val)
    return x_filled

df_final[numeric_cols] = (
    df_final.groupby(['athlete', 'Activity Type'], group_keys=False)[numeric_cols]
    .apply(fill_missing_by_group)
)

# Kolumny nienumeryczne
object_cols = df_final.select_dtypes(include='object').columns
df_final[object_cols] = df_final[object_cols].fillna('Unknown')

# Sprawdzenie rezultatow
missing_after = df_final.isnull().sum()
print("Missing values after imputation:\n", missing_after)

df_final.head()

Missing values before imputation:
 Activity Date             0
Activity Type             0
Elapsed Time              0
Distance                  0
Max Heart Rate            2
Moving Time               0
Max Speed               133
Average Speed           120
Elevation Gain          102
Elevation Loss         1008
Average Heart Rate        0
Average Temperature    4632
athlete                   0
dtype: int64
Missing values after imputation:
 Activity Date          0
Activity Type          0
Elapsed Time           0
Distance               0
Max Heart Rate         0
Moving Time            0
Max Speed              0
Average Speed          0
Elevation Gain         0
Elevation Loss         0
Average Heart Rate     0
Average Temperature    0
athlete                0
dtype: int64

,Activity Date,Activity Type,Elapsed Time,Distance,Max Heart Rate,Moving Time,Max Speed,Average Speed,Elevation Gain,Elevation Loss,Average Heart Rate,Average Temperature,athlete
99,2022-09-26 13:32:44,Run,2369,7690.0,178.0,2298,5.871,3.349,28.7,144.0,164.0,22.0,athlete_1
100,2022-09-29 08:26:02,Ride,14289,64080.0,187.0,9456,16.428,6.777,1012.7,1111.0,140.0,21.0,athlete_1
101,2022-10-01 08:57:29,Ride,28922,124020.0,184.0,17780,17.030,6.976,2312.7,2434.0,139.0,21.0,athlete_1
102,2022-10-02 08:38:09,Ride,16562,82000.0,169.0,10044,17.708,8.165,617.6,687.0,132.0,21.0,athlete_1
103,2022-10-04 05:47:05,Run,1444,5050.0,184.0,1333,5.064,3.789,0.0,65.0,158.0,22.0,athlete_1

## Adding HR Max, Activity ID and is_triathlon columns

In [16]:
df_final['HRMax'] = df_final["athlete"].map(max_hr_dict)
df_final["Activity ID"] = [i+1 for i in range(len(df_final))]


def identify_triathlon_runs(df, max_time_gap_hours=6):
    df = df.copy()
    df['is_triathlon'] = 0
    
    for athlete in df['athlete'].unique():
        athlete_data = df[df['athlete'] == athlete].sort_values('Activity Date')
        
        # Szukamy sekwencji: Ride → Run w określonym czasie
        for i in range(len(athlete_data) - 1):
            current = athlete_data.iloc[i]
            next_act = athlete_data.iloc[i + 1]
            
            if (current['Activity Type'] == 'Ride' and 
                next_act['Activity Type'] == 'Run'):
                
                time_gap = (next_act['Activity Date'] - current['Activity Date']).total_seconds() / 3600
                
                if time_gap <= max_time_gap_hours:
                    # Oznaczamy bieg jako część triathlonu
                    df.loc[next_act.name, 'is_triathlon'] = 1
    
    return df
    
df_final = identify_triathlon_runs(df_final, max_time_gap_hours=6)

# Sprawdzamy poprawność oznaczeń triathlonów
triathlon_runs = df_final[(df_final['is_triathlon'] == 1)]
print(f"Znaleziono {len(triathlon_runs)} biegów triathlonowych")
print("Rozkład po sportowcach:")
print(triathlon_runs['athlete'].value_counts())

Znaleziono 256 biegów triathlonowych
Rozkład po sportowcach:
athlete
athlete_2           144
athlete_15           76
athlete_1            18
athlete_11            3
athlete_16            3
athlete_garmin_1      3
athlete_8             2
athlete_3             2
athlete_12            2
athlete_5             1
athlete_7             1
athlete_18            1
Name: count, dtype: int64

## Races identification

In [17]:
def identify_races(df, hr_threshold=0.86, days_window=365):
    df = df.copy()
    common_race_distances = [5000, 10000, 21100, 42195]
    run_mask = df["Activity Type"] == "Run"
    run_df = df[run_mask].sort_values(["athlete", "Activity Date"])
    
    rolling_list = []
    
    for athlete, subdf in run_df.groupby("athlete"):
        subdf["Activity Date"] = pd.to_datetime(subdf["Activity Date"])
        subdf = subdf.sort_values("Activity Date").set_index("Activity Date")
        subdf["avg_distance_runner"] = subdf["Distance"].rolling(f"{days_window}D", min_periods=1).mean()
        subdf["avg_speed_runner"] = subdf["Average Speed"].rolling(f"{days_window}D", min_periods=1).mean()
        rolling_list.append(subdf.reset_index())
    
    rolling_df = pd.concat(rolling_list, ignore_index=True)
    df = df.merge(rolling_df[["Activity ID", "avg_distance_runner", "avg_speed_runner"]], on="Activity ID", how="left")
    
    # Warunki
    cond_hr = df["Average Heart Rate"] > (df["HRMax"] * hr_threshold)
    cond_distance =  df["Distance"] > 40000
    cond_speed = df["Average Speed"] > 1.4 * df["avg_speed_runner"]
    df["time_ratio"] = df["Elapsed Time"] / df["Moving Time"].replace(0, np.nan)
    cond_ratio = df["time_ratio"] <= 1.1
    
    is_triathlon = df["is_triathlon"]
    distance_tolerance = 0.1  # 10% tolerance
    is_common_distance = False
    for race_dist in common_race_distances:
        lower_bound = race_dist * (1 - distance_tolerance)
        upper_bound = race_dist * (1 + distance_tolerance)
        is_common_distance |= (df["Distance"] >= lower_bound) & (df["Distance"] <= upper_bound)

    # Race score
    df["race_score"] = cond_hr.astype(int) + cond_distance.astype(int) + cond_speed.astype(int) + is_triathlon.astype(int)

    # Dodatkowy waruenk: wyścig ma min. 3km
    cond_min_distance = df["Distance"] >= 3000

    df["race_score"] = 2*cond_hr.astype(int) + 2*cond_distance.astype(int) + 2*cond_speed.astype(int) + is_triathlon.astype(int)  + is_common_distance.astype(int)
    
    run_mask = df["Activity Type"] == "Run"
    
    # Oznaczenie wyścigow
    df["is_race"] = run_mask & cond_min_distance & (df["race_score"] >= 2 ) & cond_ratio
    
    print(f"Detected {df['is_race'].sum()} race activities out of {len(df)} total")
    return df

df = identify_races(df_final)
df = df.drop(['avg_distance_runner', 'avg_speed_runner', 'time_ratio', 'race_score'], axis=1)
df

Detected 306 race activities out of 10537 total

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

,Activity Date,Activity Type,Elapsed Time,Distance,Max Heart Rate,Moving Time,Max Speed,Average Speed,Elevation Gain,Elevation Loss,Average Heart Rate,Average Temperature,athlete,HRMax,Activity ID,is_triathlon,is_race
0,2022-09-26 13:32:44,Run,2369,7690.0,178.0,2298,5.871000,3.349000,28.7,144.0,164.0,22.0,athlete_1,204.1,1,0,False
1,2022-09-29 08:26:02,Ride,14289,64080.0,187.0,9456,16.428000,6.777000,1012.7,1111.0,140.0,21.0,athlete_1,204.1,2,0,False
2,2022-10-01 08:57:29,Ride,28922,124020.0,184.0,17780,17.030000,6.976000,2312.7,2434.0,139.0,21.0,athlete_1,204.1,3,0,False
3,2022-10-02 08:38:09,Ride,16562,82000.0,169.0,10044,17.708000,8.165000,617.6,687.0,132.0,21.0,athlete_1,204.1,4,0,False
4,2022-10-04 05:47:05,Run,1444,5050.0,184.0,1333,5.064000,3.789000,0.0,65.0,158.0,22.0,athlete_1,204.1,5,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10532,2024-09-25 17:20:25,Ride,3855,20410.0,142.0,3662,1.473765,5.305556,69.0,66.0,115.0,22.5,athlete_garmin_2,185.7,10533,0,False
10533,2024-09-23 17:18:37,Ride,4571,20020.0,173.0,3833,1.219136,4.388889,81.0,69.0,127.0,22.5,athlete_garmin_2,185.7,10534,0,False
10534,2024-09-22 16:07:15,Ride,8115,23730.0,145.0,4504,0.810185,2.916667,82.0,77.0,106.0,23.0,athlete_garmin_2,185.7,10535,0,False
10535,2024-09-21 08:21:28,Ride,4266,20060.0,172.0,3756,1.304012,4.694444,73.0,70.0,134.0,18.0,athlete_garmin_2,185.7,10536,0,False
10536,2024-09-20 16:59:31,Ride,5300,24740.0,157.0,4966,1.296296,4.666667,77.0,74.0,126.0,21.0,athlete_garmin_2,185.7,10537,0,False

## Stats calculation

In [18]:
# === Statystyki ===

# liczba startów w roku
df_stat = df.copy()
df_stat["year"] = df["Activity Date"].dt.year
race_stats = df_stat[df_stat["is_race"]].groupby(["athlete", "year"]).size().reset_index(name="races_per_year")

# średnia liczba godzin aktywności tygodniowo
df_stat["week"] = df_stat["Activity Date"].dt.isocalendar().week
weekly_hours = (
    df_stat.groupby(["athlete", "year", "week"])["Elapsed Time"]
    .sum()
    .groupby("athlete")
    .mean()
    .reset_index(name="avg_weekly_hours")
)
weekly_hours = weekly_hours["avg_weekly_hours"]/3600

print("\n Statystyki:")
print("- Liczba startów w roku:")
print(race_stats)
print("\n- Średnia liczba godzin aktywności tygodniowo:")
print(weekly_hours)

df

 Statystyki:
- Liczba startów w roku:
             athlete  year  races_per_year
0          athlete_1  2022               2
1          athlete_1  2023               6
2          athlete_1  2024               2
3          athlete_1  2025               3
4         athlete_11  2021               2
5         athlete_11  2022               2
6         athlete_11  2023               3
7         athlete_11  2024               3
8         athlete_13  2023              13
9         athlete_13  2024              22
10        athlete_13  2025               7
11        athlete_14  2025              20
12        athlete_15  2020               3
13        athlete_15  2021              13
14        athlete_15  2022               6
15        athlete_15  2023               4
16        athlete_15  2024               5
17        athlete_15  2025               3
18        athlete_16  2021               2
19        athlete_16  2022               2
20        athlete_16  2023               3
21        athlete_16  2024               3
22        athlete_17  2025              22
23        athlete_18  2025               1
24         athlete_2  2021               3
25         athlete_2  2022               3
26         athlete_2  2023               5
27         athlete_2  2024               7
28         athlete_2  2025              23
29         athlete_3  2023               6
30         athlete_3  2024              13
31         athlete_3  2025               6
32         athlete_4  2025               2
33         athlete_5  2022               1
34         athlete_5  2023               3
35         athlete_5  2025               3
36         athlete_7  2024               8
37         athlete_7  2025              13
38         athlete_8  2021               3
39         athlete_8  2022               9
40         athlete_8  2023               2
41         athlete_9  2025              34
42  athlete_garmin_1  2024               1
43  athlete_garmin_1  2025               5
44  athlete_garmin_2  2024               1
45  athlete_garmin_2  2025               3

- Średnia liczba godzin aktywności tygodniowo:
0      8.725913
1      5.335996
2     13.799151
3      5.154803
4      3.019389
5      9.045905
6      5.335996
7      6.756898
8      9.133440
9      8.354268
10     7.906403
11     9.658280
12     5.838820
13     8.297470
14     7.933693
15     3.042674
16     6.719735
17     2.981554
Name: avg_weekly_hours, dtype: float64

,Activity Date,Activity Type,Elapsed Time,Distance,Max Heart Rate,Moving Time,Max Speed,Average Speed,Elevation Gain,Elevation Loss,Average Heart Rate,Average Temperature,athlete,HRMax,Activity ID,is_triathlon,is_race
0,2022-09-26 13:32:44,Run,2369,7690.0,178.0,2298,5.871000,3.349000,28.7,144.0,164.0,22.0,athlete_1,204.1,1,0,False
1,2022-09-29 08:26:02,Ride,14289,64080.0,187.0,9456,16.428000,6.777000,1012.7,1111.0,140.0,21.0,athlete_1,204.1,2,0,False
2,2022-10-01 08:57:29,Ride,28922,124020.0,184.0,17780,17.030000,6.976000,2312.7,2434.0,139.0,21.0,athlete_1,204.1,3,0,False
3,2022-10-02 08:38:09,Ride,16562,82000.0,169.0,10044,17.708000,8.165000,617.6,687.0,132.0,21.0,athlete_1,204.1,4,0,False
4,2022-10-04 05:47:05,Run,1444,5050.0,184.0,1333,5.064000,3.789000,0.0,65.0,158.0,22.0,athlete_1,204.1,5,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10532,2024-09-25 17:20:25,Ride,3855,20410.0,142.0,3662,1.473765,5.305556,69.0,66.0,115.0,22.5,athlete_garmin_2,185.7,10533,0,False
10533,2024-09-23 17:18:37,Ride,4571,20020.0,173.0,3833,1.219136,4.388889,81.0,69.0,127.0,22.5,athlete_garmin_2,185.7,10534,0,False
10534,2024-09-22 16:07:15,Ride,8115,23730.0,145.0,4504,0.810185,2.916667,82.0,77.0,106.0,23.0,athlete_garmin_2,185.7,10535,0,False
10535,2024-09-21 08:21:28,Ride,4266,20060.0,172.0,3756,1.304012,4.694444,73.0,70.0,134.0,18.0,athlete_garmin_2,185.7,10536,0,False
10536,2024-09-20 16:59:31,Ride,5300,24740.0,157.0,4966,1.296296,4.666667,77.0,74.0,126.0,21.0,athlete_garmin_2,185.7,10537,0,False

In [19]:
df.dtypes

Activity Date          datetime64[ns]
Activity Type                  object
Elapsed Time                    int64
Distance                      float64
Max Heart Rate                float64
Moving Time                     int64
Max Speed                     float64
Average Speed                 float64
Elevation Gain                float64
Elevation Loss                float64
Average Heart Rate            float64
Average Temperature           float64
athlete                        object
HRMax                         float64
Activity ID                     int64
is_triathlon                    int64
is_race                          bool
dtype: object

In [20]:
print(len(df[(df['is_triathlon'] == 1) & (df['is_race'] == 1)]))
df[(df["Distance"] >= 40000) & (df['Activity Type'] == 'Run')]

47

,Activity Date,Activity Type,Elapsed Time,Distance,Max Heart Rate,Moving Time,Max Speed,Average Speed,Elevation Gain,Elevation Loss,Average Heart Rate,Average Temperature,athlete,HRMax,Activity ID,is_triathlon,is_race
2694,2024-04-14 07:04:47,Run,15071,42430.0,182.0,15070,5.452,2.816,169.0,154.0,164.0,21.0,athlete_3,188.1,2695,0,True
2838,2024-09-29 07:24:59,Run,12592,42290.0,170.0,12580,5.150,3.362,69.0,66.0,160.0,20.0,athlete_3,188.1,2839,0,True
3738,2025-05-11 07:37:08,Run,12568,42790.0,186.0,12568,5.100,3.405,78.0,85.0,170.0,22.0,athlete_5,197.2,3739,0,True
6078,2024-04-14 07:07:31,Run,14000,42580.0,185.0,13991,5.230,3.044,113.5,221.0,176.0,29.0,athlete_13,200.4,6079,0,True
9000,2025-09-13 06:01:07,Run,17615,40420.0,201.0,16353,4.900,2.472,1394.0,1339.0,173.0,26.0,athlete_15,216.2,9001,0,True
9369,2025-04-06 07:05:45,Run,12939,42380.0,171.0,12888,6.200,3.289,269.2,270.8,150.0,22.0,athlete_17,178.1,9370,0,True
9575,2025-09-28 07:00:53,Run,11150,42390.0,178.0,11145,5.940,3.804,238.0,238.6,166.0,22.0,athlete_17,178.1,9576,0,True
10065,2025-10-19 08:00:11,Run,12400,42360.0,190.0,12327,4.480,3.437,137.0,130.0,175.0,16.5,athlete_18,227.0,10066,0,True

## Build training sequences

In [21]:
from sklearn.model_selection import train_test_split


def build_sequences_and_statics_split(df, days_window=365, test_split=0.2, min_runs=3):
    """
    Returns:
      - train/test split of (X_seq, X_static_df, y, meta)
      ensuring no data leakage between train/test.
    """
    df = df.sort_values(["athlete", "Activity Date"]).reset_index(drop=True)

    numeric_cols = [
        "Distance", "Elapsed Time", "Moving Time", "Average Speed", "Max Speed",
        "Average Heart Rate", "Max Heart Rate", "Elevation Gain", "Elevation Loss",
        "Average Temperature", "is_triathlon"
    ]
    df[numeric_cols] = df[numeric_cols].astype(np.float32)

    seqs, statics, ys, metas, splits = [], [], [], [], []

    # grupowanie per athlete
    for athlete, sub in df.groupby("athlete"):
        sub = sub.sort_values("Activity Date").reset_index(drop=True)
        runs = sub[sub["Activity Type"].str.lower() == "run"].copy()
        races = runs[runs["is_race"]].copy()
        if races.empty:
            continue

        # Podział na train/test chronologicznie by zapobiec wyciekowi danych testowych 
        races = races.sort_values("Activity Date")
        n_test = max(1, int(len(races) * test_split))
        test_races = races.tail(n_test)
        train_races = races.head(len(races) - n_test)

        for r, split in [*[(r, "train") for _, r in train_races.iterrows()],
                         *[(r, "test")  for _, r in test_races.iterrows()]]:
            race_date = r["Activity Date"]
        
            # Tylko treningi przez wyścigiem (brak wycieku danych)
            mask = (runs["Activity Date"] >= race_date - pd.Timedelta(days=days_window)) & \
                   (runs["Activity Date"] < race_date)
            window_runs = runs.loc[mask].copy()
            if len(window_runs) < min_runs:
                continue

            window_runs["days_to_race"] = (race_date - window_runs["Activity Date"]).dt.days

            seq_numeric_feats = [
                "days_to_race", "Distance", "Elapsed Time", "Moving Time",
                "Average Speed", "Max Speed", "Average Heart Rate", "Max Heart Rate",
                "Elevation Gain", "Elevation Loss", "Average Temperature"
            ]
                    
            # Osobne arrays dla numeric  features
            seq_array = window_runs[seq_numeric_feats].to_numpy(dtype=np.float32)

            # Agregacja statystyk 
            window_others = sub[(sub["Activity Type"].str.lower() != "run") &
                                (sub["Activity Date"] >= race_date - pd.Timedelta(days=days_window)) &
                                (sub["Activity Date"] <= race_date)]

            def agg_activity(df_, names):
                sel = df_["Activity Type"].str.lower().isin(names)
                return (
                    float(df_.loc[sel, "Elapsed Time"].sum(min_count=1) or 0.0),
                    float(df_.loc[sel, "Distance"].sum(min_count=1) or 0.0),
                    int(sel.sum())
                )

            swim_t, swim_dist, swim_sessions = agg_activity(window_others, ["swim"])
            bike_t, bike_dist, bike_sessions = agg_activity(window_others, ["ride"])
            gym_t, _, gym_sessions = agg_activity(window_others, ["weight training"])

            years_of_exp = (
                (runs["Activity Date"].max() - runs["Activity Date"].min()).days / 365.0
                if runs.shape[0] > 1 else 0.0
            )

            static = {
                "athlete": athlete,
                "lead_to_race_date": race_date,
                "years_of_experience": years_of_exp,
                "swim_t_total": swim_t,
                "swim_dist_total": swim_dist,
                "swim_sessions": swim_sessions,
                "bike_t_total": bike_t,
                "bike_dist_total": bike_dist,
                "bike_sessions": bike_sessions,
                "gym_t_total": gym_t,
                "gym_sessions": gym_sessions,
                "race_distance_m": float(r["Distance"]),
                "race_elevation_gain_m": float(r["Elevation Gain"]),
                "is_triathlon": float(r["is_triathlon"]),
                "split": split
            }

            # Przewidywane tempo (sec/km)
            y_val = r.get("Moving Time", r.get("Elapsed Time", None))
            if pd.isna(y_val) or y_val is None:
                continue
            pace_sec_per_km = float(y_val) / (float(r["Distance"]) / 1000.0)

            seqs.append(seq_array)
            statics.append(static)
            ys.append(pace_sec_per_km)
            metas.append({
                "athlete": athlete,
                "lead_to_race_date": race_date,
                "race_activity_id": r.get("Activity ID"),
                "race_distance_m": float(r["Distance"]),
                "split": split
            })
            splits.append(split)

    # Grupowanie na test/train 
    df_stat = pd.DataFrame(statics)
    df_meta = pd.DataFrame(metas)
    y = np.array(ys, dtype=np.float32)

    train_mask = df_stat["split"] == "train"
    test_mask  = df_stat["split"] == "test"

    train_seqs = [s for s, sp in zip(seqs, splits) if sp == "train"]
    test_seqs  = [s for s, sp in zip(seqs, splits) if sp == "test"]

    train_stat_df = df_stat.loc[train_mask].drop(columns="split").reset_index(drop=True)
    test_stat_df  = df_stat.loc[test_mask].drop(columns="split").reset_index(drop=True)

    train_y = y[train_mask.values]
    test_y  = y[test_mask.values]

    train_meta = df_meta.loc[train_mask].reset_index(drop=True)
    test_meta  = df_meta.loc[test_mask].reset_index(drop=True)

    print(f"Built sequences: total={len(seqs)}, train={len(train_seqs)}, test={len(test_seqs)}")
    return (train_seqs, train_stat_df, train_y, train_meta), (test_seqs, test_stat_df, test_y, test_meta)

In [22]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.preprocessing.sequence import pad_sequences
import joblib

from sklearn.preprocessing import StandardScaler
from tensorflow.keras.preprocessing.sequence import pad_sequences
import joblib

def scale_and_pad(train_seqs, test_seqs, train_stat_df, test_stat_df, train_y, test_y,
                          static_numeric_cols, static_binary_cols,
                          seq_numeric_dim,  
                          pad_value=999.0):
    
    # Dla static features 
    static_scaler = StandardScaler()
    
    # Skaluj tylko numeric features
    X_static_train_numeric = static_scaler.fit_transform(train_stat_df[static_numeric_cols].values)
    X_static_test_numeric = static_scaler.transform(test_stat_df[static_numeric_cols].values)
    
    # Binary features bez skalowania (już są 0/1)
    X_static_train_binary = train_stat_df[static_binary_cols].values.astype(float)
    X_static_test_binary = test_stat_df[static_binary_cols].values.astype(float)
    
    # Połączenie numeric + binary
    X_static_train = np.column_stack([X_static_train_numeric, X_static_train_binary])
    X_static_test = np.column_stack([X_static_test_numeric, X_static_test_binary])

    # Dla sequence features 
    seq_scaler = StandardScaler()
    
    # Połączenie sekwencji do skalowania
    all_sequence_data = np.vstack([s for s in train_seqs if len(s) > 0])
    seq_scaler.fit(all_sequence_data)
    
    train_seqs_scaled = [seq_scaler.transform(s) if len(s) > 0 else np.empty((0, seq_numeric_dim)) 
                        for s in train_seqs]
    test_seqs_scaled = [seq_scaler.transform(s) if len(s) > 0 else np.empty((0, seq_numeric_dim)) 
                       for s in test_seqs]

    # Pad sequences
    max_len = max(max(len(s) for s in train_seqs_scaled), max(len(s) for s in test_seqs_scaled))
    
    X_seq_train = pad_sequences(train_seqs_scaled, maxlen=max_len, padding="post", value=pad_value)
    X_seq_test = pad_sequences(test_seqs_scaled, maxlen=max_len, padding="post", value=pad_value)

    # Scale target
    y_scaler = StandardScaler()
    y_train_scaled = y_scaler.fit_transform(train_y.reshape(-1, 1)).flatten()
    y_test_scaled = y_scaler.transform(test_y.reshape(-1, 1)).flatten()

    scalers = {"seq": seq_scaler, "static": static_scaler, "y": y_scaler}
    
    print(f" Scaled and padded shapes:")
    print(f"   X_seq_train: {X_seq_train.shape}")
    print(f"   X_seq_test:  {X_seq_test.shape}")
    print(f"   X_static_train: {X_static_train.shape} (numeric: {len(static_numeric_cols)}, binary: {len(static_binary_cols)})")
    print(f"   X_static_test:  {X_static_test.shape}")
    print(f"   y_train: {y_train_scaled.shape}")
    print(f"   y_test:  {y_test_scaled.shape}")
    print(f"   Max sequence length: {max_len}")
    
    return X_seq_train, X_seq_test, X_static_train, X_static_test, y_train_scaled, y_test_scaled, scalers

2025-11-15 16:59:14.292332: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1763225954.316243  130811 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1763225954.323418  130811 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

## Scaling

In [23]:
(train_seqs, train_stat_df, train_y, train_meta), (test_seqs, test_stat_df, test_y, test_meta) = build_sequences_and_statics_split(df)

static_numeric_cols = [
    "years_of_experience", "swim_t_total", "swim_dist_total", "swim_sessions",
    "bike_t_total", "bike_dist_total", "bike_sessions",
    "gym_t_total", "gym_sessions",
    "race_distance_m", "race_elevation_gain_m"
]

static_binary_cols = [
    "is_triathlon"
]

seq_numeric_dim = 11


(X_seq_train, X_seq_test, X_static_train, X_static_test, y_train_scaled, y_test_scaled, scalers) = \
      scale_and_pad(train_seqs, test_seqs, train_stat_df, test_stat_df, train_y, test_y,
                    static_numeric_cols, static_binary_cols,
                    seq_numeric_dim)

X_static_train = np.nan_to_num(X_static_train, nan=0.0)
X_static_test = np.nan_to_num(X_static_test, nan=0.0)

joblib.dump(scalers["seq"], "scaler_seq.pkl")
joblib.dump(scalers["static"], "scaler_static.pkl")
joblib.dump(scalers["y"], "scaler_y.pkl")

Built sequences: total=300, train=242, test=58
 Scaled and padded shapes:
   X_seq_train: (242, 232, 11)
   X_seq_test:  (58, 232, 11)
   X_static_train: (242, 12) (numeric: 11, binary: 1)
   X_static_test:  (58, 12)
   y_train: (242,)
   y_test:  (58,)
   Max sequence length: 232

['scaler_y.pkl']

# Model

In [24]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, GRU, Dense, Dropout, concatenate, BatchNormalization, Masking, Bidirectional
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import mean_absolute_error, mean_squared_error


def build_gru_race_model(seq_shape, static_shape, hidden_size=16, dense_units=32, dropout_rate=0.3):
    """
    seq_shape: (max_seq_len, n_seq_features)
    static_shape: (n_static_features,)
    """
    # Sequential branch
    seq_input = Input(shape=seq_shape, name="seq_input")
    x = Masking(mask_value=999.0)(seq_input)
    x = Bidirectional(GRU(hidden_size, return_sequences=True, kernel_regularizer="l2", name="gru_1"))(x)
    x = Dropout(dropout_rate)(x)
    x = BatchNormalization()(x)
    x = Bidirectional(GRU(hidden_size, return_sequences=False, kernel_regularizer="l2", name="gru_2"))(x)
    x = Dense(dense_units, activation="relu", kernel_regularizer="l2")(x)
    x = BatchNormalization()(x)
    x = Dropout(dropout_rate)(x)

    # Static branch
    static_input = Input(shape=static_shape, name="static_input")
    s = Dense(dense_units, activation="relu", kernel_regularizer="l2")(static_input)
    s = BatchNormalization()(s)
    s = Dropout(dropout_rate)(s)

    # Merge branches 
    merged = concatenate([x, s])
    merged = Dense(dense_units, activation="relu", kernel_regularizer="l2")(merged)
    merged = BatchNormalization()(merged)
    merged = Dropout(dropout_rate)(merged)

    #Output
    output = Dense(1, activation="linear", name="pace_sec_per_km")(merged)

    # Model
    model = Model(inputs=[seq_input, static_input], outputs=output)
    model.compile(
        optimizer=Adam(learning_rate=8e-4),
        loss="mae",
        metrics=["mae", "mse", "mape"]
    )

    return model
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    # avoid division by zero
    non_zero_mask = y_true != 0
    return np.mean(np.abs((y_true[non_zero_mask] - y_pred[non_zero_mask]) / y_true[non_zero_mask])) * 100
    
def evaluate(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    nrmse = rmse / np.mean(y_true)
    mape = mean_absolute_percentage_error(y_true, y_pred)
    return mae, rmse, nrmse, mape

In [25]:
seq_shape = (X_seq_train.shape[1], X_seq_train.shape[2])
static_shape = (X_static_train.shape[1],)

X_static_train = np.nan_to_num(X_static_train, nan=0.0)
X_static_test = np.nan_to_num(X_static_test, nan=0.0)

model = build_gru_race_model(seq_shape, static_shape)
model.summary()

I0000 00:00:1763225958.843562  130811 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15513 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ seq_input           │ (None, 232, 11)   │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal           │ (None, 232, 11)   │          0 │ seq_input[0][0]   │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ masking (Masking)   │ (None, 232, 11)   │          0 │ seq_input[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ any (Any)           │ (None, 232)       │          0 │ not_equal[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional       │ (None, 232, 32)   │      2,784 │ masking[0][0],    │
│ (Bidirectional)     │                   │            │ any[0][0]         │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 232, 32)   │          0 │ bidirectional[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 232, 32)   │        128 │ dropout[0][0],    │
│ (BatchNormalizatio… │                   │            │ any[0][0]         │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_1     │ (None, 32)        │      4,800 │ batch_normalizat… │
│ (Bidirectional)     │                   │            │ any[0][0]         │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ static_input        │ (None, 12)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 32)        │      1,056 │ bidirectional_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 32)        │        416 │ static_input[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32)        │        128 │ dense[0][0]       │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32)        │        128 │ dense_1[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 32)        │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 32)        │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 64)        │          0 │ dropout_1[0][0],  │
│ (Concatenate)       │                   │            │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 32)        │      2,080 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32)        │        128 │ dense_2[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 32)        │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ pace_sec_per_km     │ (None, 1)         │         33 │ dropout_3[0][0]   │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 11,681 (45.63 KB)

 Trainable params: 11,425 (44.63 KB)

 Non-trainable params: 256 (1.00 KB)

## Training

In [26]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
early_stop = EarlyStopping(monitor="val_loss", patience=50, restore_best_weights=True)
checkpoint = ModelCheckpoint("best_gru_model.h5", save_best_only=True, monitor="val_loss")


history = model.fit(
    [X_seq_train, X_static_train],
    y_train_scaled,
    validation_split=0.2,
    epochs=500,
    batch_size=16,
    callbacks=[early_stop, checkpoint],
    shuffle=True,
    verbose=1
)

y_pred_scaled = model.predict([X_seq_test, X_static_test])
y_pred = scalers["y"].inverse_transform(y_pred_scaled).flatten()  # tempo sec/km przewidywane
y_true = test_y.flatten()  # originalne tempo sec/km

Epoch 1/500

I0000 00:00:1763225968.908352  130860 cuda_dnn.cc:529] Loaded cuDNN version 90300

13/13 ━━━━━━━━━━━━━━━━━━━━ 12s 128ms/step - loss: 3.5243 - mae: 1.5035 - mape: 869.9703 - mse: 3.8799 - val_loss: 3.3269 - val_mae: 1.3338 - val_mape: 90.7900 - val_mse: 2.3240
Epoch 2/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 3.2454 - mae: 1.2609 - mape: 1371.9043 - mse: 2.4211 - val_loss: 3.3363 - val_mae: 1.3781 - val_mape: 89.5589 - val_mse: 2.5227
Epoch 3/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 3.1732 - mae: 1.2235 - mape: 1493.1007 - mse: 2.3584 - val_loss: 3.3304 - val_mae: 1.4067 - val_mape: 90.8642 - val_mse: 2.6308
Epoch 4/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 3.1084 - mae: 1.1930 - mape: 4016.7229 - mse: 2.1807 - val_loss: 3.3219 - val_mae: 1.4317 - val_mape: 92.1611 - val_mse: 2.7290
Epoch 5/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 2.8349 - mae: 0.9526 - mape: 580.0377 - mse: 1.5520 - val_loss: 3.3007 - val_mae: 1.4430 - val_mape: 93.0479 - val_mse: 2.7774
Epoch 6/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 2.9102 - mae: 1.0602 - mape: 1506.7024 - mse: 1.9005 - val_loss: 3.2668 - val_mae: 1.4409 - val_mape: 92.6105 - val_mse: 2.7767
Epoch 7/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 2.8331 - mae: 1.0147 - mape: 2296.0347 - mse: 1.5441 - val_loss: 3.2509 - val_mae: 1.4554 - val_mape: 92.0687 - val_mse: 2.8508
Epoch 8/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 2.7728 - mae: 0.9844 - mape: 1690.9370 - mse: 1.6082 - val_loss: 3.2485 - val_mae: 1.4821 - val_mape: 92.4861 - val_mse: 2.9735
Epoch 9/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 2.7477 - mae: 0.9883 - mape: 2410.3640 - mse: 1.5098 - val_loss: 3.2355 - val_mae: 1.4980 - val_mape: 93.4316 - val_mse: 3.0427
Epoch 10/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 2.6574 - mae: 0.9267 - mape: 733.1790 - mse: 1.3982 - val_loss: 3.2399 - val_mae: 1.5302 - val_mape: 95.3947 - val_mse: 3.1738
Epoch 11/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 2.6500 - mae: 0.9468 - mape: 619.6168 - mse: 1.4690 - val_loss: 3.1991 - val_mae: 1.5161 - val_mape: 93.6303 - val_mse: 3.1210
Epoch 12/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 2.5227 - mae: 0.8459 - mape: 792.4063 - mse: 1.1541 - val_loss: 3.1611 - val_mae: 1.5033 - val_mape: 93.0082 - val_mse: 3.0680
Epoch 13/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 2.4222 - mae: 0.7705 - mape: 1065.0288 - mse: 1.0358 - val_loss: 3.1317 - val_mae: 1.4985 - val_mape: 93.1327 - val_mse: 3.0486
Epoch 14/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 2.4731 - mae: 0.8458 - mape: 2157.5916 - mse: 1.2305 - val_loss: 3.0420 - val_mae: 1.4334 - val_mape: 89.5485 - val_mse: 2.7932
Epoch 15/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 2.4663 - mae: 0.8635 - mape: 371.9708 - mse: 1.3356 - val_loss: 2.9974 - val_mae: 1.4127 - val_mape: 88.5357 - val_mse: 2.7210
Epoch 16/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 2.3240 - mae: 0.7449 - mape: 799.6615 - mse: 0.8916 - val_loss: 2.9779 - val_mae: 1.4162 - val_mape: 88.2131 - val_mse: 2.7401
Epoch 17/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 2.3116 - mae: 0.7553 - mape: 898.2501 - mse: 0.9386 - val_loss: 2.9773 - val_mae: 1.4375 - val_mape: 90.2729 - val_mse: 2.8248
Epoch 18/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 2.2962 - mae: 0.7617 - mape: 1043.7258 - mse: 0.9608 - val_loss: 2.9466 - val_mae: 1.4284 - val_mape: 89.9544 - val_mse: 2.7979
Epoch 19/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 2.2878 - mae: 0.7747 - mape: 751.8859 - mse: 1.0048 - val_loss: 2.9334 - val_mae: 1.4362 - val_mape: 92.7841 - val_mse: 2.8005
Epoch 20/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 2.2078 - mae: 0.7156 - mape: 884.2021 - mse: 0.8332 - val_loss: 2.8785 - val_mae: 1.4018 - val_mape: 90.8757 - val_mse: 2.6794
Epoch 21/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 2.2340 - mae: 0.7622 - mape: 1899.1890 - mse: 0.8517 - val_loss: 2.8542 - val_mae: 1.3975 - val_mape: 91.4014 - val_mse: 2.6575
Epoch 22/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 2.1558 - mae: 0.7039 - mape: 922.2225 - mse: 0.8407 - val_loss: 2.7881 - val_mae: 1.3509 - val_mape: 87.8870 - val_mse: 2.4968
Epoch 23/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 2.1063 - mae: 0.6737 - mape: 790.2881 - mse: 0.7405 - val_loss: 2.7244 - val_mae: 1.3062 - val_mape: 85.8481 - val_mse: 2.3462
Epoch 24/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 2.1414 - mae: 0.7278 - mape: 654.8357 - mse: 0.8241 - val_loss: 2.6975 - val_mae: 1.2978 - val_mape: 84.8851 - val_mse: 2.3189
Epoch 25/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 2.1454 - mae: 0.7501 - mape: 1506.3958 - mse: 0.9213 - val_loss: 2.6876 - val_mae: 1.3059 - val_mape: 85.7942 - val_mse: 2.3318
Epoch 26/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 2.0199 - mae: 0.6425 - mape: 5622.5127 - mse: 0.6978 - val_loss: 2.6993 - val_mae: 1.3352 - val_mape: 87.4967 - val_mse: 2.4264
Epoch 27/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 2.0532 - mae: 0.6933 - mape: 560.4185 - mse: 0.7380 - val_loss: 2.6376 - val_mae: 1.2907 - val_mape: 85.1027 - val_mse: 2.2693
Epoch 28/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.9578 - mae: 0.6151 - mape: 594.4810 - mse: 0.6139 - val_loss: 2.5704 - val_mae: 1.2407 - val_mape: 81.8859 - val_mse: 2.1077
Epoch 29/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.9971 - mae: 0.6714 - mape: 634.3778 - mse: 0.7535 - val_loss: 2.5237 - val_mae: 1.2106 - val_mape: 79.0369 - val_mse: 2.0139
Epoch 30/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.9594 - mae: 0.6502 - mape: 877.6068 - mse: 0.6596 - val_loss: 2.4913 - val_mae: 1.1945 - val_mape: 76.9932 - val_mse: 1.9581
Epoch 31/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 2.0287 - mae: 0.7357 - mape: 1219.2772 - mse: 0.8389 - val_loss: 2.4960 - val_mae: 1.2149 - val_mape: 79.0045 - val_mse: 2.0123
Epoch 32/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.9477 - mae: 0.6703 - mape: 901.5226 - mse: 0.7568 - val_loss: 2.5188 - val_mae: 1.2533 - val_mape: 84.0965 - val_mse: 2.1091
Epoch 33/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.9170 - mae: 0.6552 - mape: 4338.6196 - mse: 0.6972 - val_loss: 2.4968 - val_mae: 1.2467 - val_mape: 83.0445 - val_mse: 2.0847
Epoch 34/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.8062 - mae: 0.5597 - mape: 1927.6898 - mse: 0.5175 - val_loss: 2.4687 - val_mae: 1.2334 - val_mape: 81.2634 - val_mse: 2.0459
Epoch 35/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.8033 - mae: 0.5716 - mape: 640.2567 - mse: 0.5795 - val_loss: 2.4252 - val_mae: 1.2047 - val_mape: 77.7804 - val_mse: 1.9669
Epoch 36/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.7343 - mae: 0.5173 - mape: 327.7098 - mse: 0.4484 - val_loss: 2.4021 - val_mae: 1.1961 - val_mape: 77.0068 - val_mse: 1.9452
Epoch 37/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.7081 - mae: 0.5056 - mape: 1087.0203 - mse: 0.4255 - val_loss: 2.3885 - val_mae: 1.1968 - val_mape: 76.9304 - val_mse: 1.9486
Epoch 38/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.7622 - mae: 0.5739 - mape: 453.0051 - mse: 0.5832 - val_loss: 2.4100 - val_mae: 1.2324 - val_mape: 79.1982 - val_mse: 2.0609
Epoch 39/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.7806 - mae: 0.6064 - mape: 846.0567 - mse: 0.5822 - val_loss: 2.3879 - val_mae: 1.2242 - val_mape: 78.3893 - val_mse: 2.0367
Epoch 40/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.7158 - mae: 0.5555 - mape: 434.2530 - mse: 0.5957 - val_loss: 2.3680 - val_mae: 1.2181 - val_mape: 78.6606 - val_mse: 2.0049
Epoch 41/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.7059 - mae: 0.5594 - mape: 952.6476 - mse: 0.5856 - val_loss: 2.3757 - val_mae: 1.2395 - val_mape: 81.5320 - val_mse: 2.0604
Epoch 42/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.6840 - mae: 0.5510 - mape: 325.5034 - mse: 0.4668 - val_loss: 2.2904 - val_mae: 1.1674 - val_mape: 75.5920 - val_mse: 1.8571
Epoch 43/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.6166 - mae: 0.4968 - mape: 387.9626 - mse: 0.4102 - val_loss: 2.2740 - val_mae: 1.1640 - val_mape: 75.3550 - val_mse: 1.8513
Epoch 44/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.6545 - mae: 0.5477 - mape: 558.4241 - mse: 0.4941 - val_loss: 2.3217 - val_mae: 1.2246 - val_mape: 81.3731 - val_mse: 2.0232
Epoch 45/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.5725 - mae: 0.4785 - mape: 561.5273 - mse: 0.3455 - val_loss: 2.3429 - val_mae: 1.2584 - val_mape: 82.4989 - val_mse: 2.1372
Epoch 46/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.5994 - mae: 0.5179 - mape: 569.0699 - mse: 0.4733 - val_loss: 2.2990 - val_mae: 1.2268 - val_mape: 79.0217 - val_mse: 2.0463
Epoch 47/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.5505 - mae: 0.4813 - mape: 526.8546 - mse: 0.3735 - val_loss: 2.2792 - val_mae: 1.2192 - val_mape: 80.3469 - val_mse: 1.9989
Epoch 48/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.5548 - mae: 0.4978 - mape: 620.8480 - mse: 0.4020 - val_loss: 2.2527 - val_mae: 1.2048 - val_mape: 79.6066 - val_mse: 1.9455
Epoch 49/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.5318 - mae: 0.4868 - mape: 1341.1713 - mse: 0.4098 - val_loss: 2.2326 - val_mae: 1.1968 - val_mape: 79.9763 - val_mse: 1.9120
Epoch 50/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.5268 - mae: 0.4939 - mape: 345.1942 - mse: 0.3933 - val_loss: 2.2240 - val_mae: 1.2002 - val_mape: 79.6299 - val_mse: 1.9230
Epoch 51/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.4897 - mae: 0.4688 - mape: 272.7556 - mse: 0.3887 - val_loss: 2.1936 - val_mae: 1.1815 - val_mape: 77.7986 - val_mse: 1.8685
Epoch 52/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.4989 - mae: 0.4896 - mape: 998.8645 - mse: 0.3953 - val_loss: 2.1668 - val_mae: 1.1662 - val_mape: 77.5528 - val_mse: 1.8189
Epoch 53/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.4466 - mae: 0.4488 - mape: 432.9464 - mse: 0.3073 - val_loss: 2.1434 - val_mae: 1.1543 - val_mape: 76.6335 - val_mse: 1.7850
Epoch 54/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.4983 - mae: 0.5120 - mape: 399.7396 - mse: 0.4701 - val_loss: 2.1465 - val_mae: 1.1688 - val_mape: 77.3704 - val_mse: 1.8244
Epoch 55/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.4341 - mae: 0.4591 - mape: 734.5558 - mse: 0.3318 - val_loss: 2.1710 - val_mae: 1.2046 - val_mape: 79.3080 - val_mse: 1.9331
Epoch 56/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.3616 - mae: 0.3979 - mape: 560.5465 - mse: 0.2503 - val_loss: 2.2049 - val_mae: 1.2496 - val_mape: 82.5281 - val_mse: 2.0703
Epoch 57/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.4155 - mae: 0.4629 - mape: 683.1276 - mse: 0.3826 - val_loss: 2.1884 - val_mae: 1.2439 - val_mape: 82.0006 - val_mse: 2.0490
Epoch 58/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.3384 - mae: 0.3965 - mape: 857.1013 - mse: 0.2973 - val_loss: 2.1268 - val_mae: 1.1931 - val_mape: 76.4228 - val_mse: 1.9049
Epoch 59/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.3880 - mae: 0.4568 - mape: 381.5662 - mse: 0.3178 - val_loss: 2.1211 - val_mae: 1.1979 - val_mape: 76.8270 - val_mse: 1.9142
Epoch 60/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.3420 - mae: 0.4213 - mape: 522.5609 - mse: 0.2920 - val_loss: 2.1416 - val_mae: 1.2289 - val_mape: 78.8763 - val_mse: 2.0133
Epoch 61/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.3537 - mae: 0.4435 - mape: 442.2044 - mse: 0.3836 - val_loss: 2.0837 - val_mae: 1.1815 - val_mape: 75.6759 - val_mse: 1.8633
Epoch 62/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.3270 - mae: 0.4272 - mape: 890.9938 - mse: 0.2987 - val_loss: 2.0811 - val_mae: 1.1893 - val_mape: 76.8446 - val_mse: 1.8871
Epoch 63/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.3285 - mae: 0.4391 - mape: 1245.5619 - mse: 0.3403 - val_loss: 2.1195 - val_mae: 1.2379 - val_mape: 80.6343 - val_mse: 2.0400
Epoch 64/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.3393 - mae: 0.4601 - mape: 357.7982 - mse: 0.4569 - val_loss: 2.1292 - val_mae: 1.2578 - val_mape: 81.0814 - val_mse: 2.1125
Epoch 65/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.2631 - mae: 0.3942 - mape: 287.5327 - mse: 0.2797 - val_loss: 2.1306 - val_mae: 1.2694 - val_mape: 82.3558 - val_mse: 2.1513
Epoch 66/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.3488 - mae: 0.4900 - mape: 1253.4086 - mse: 0.4170 - val_loss: 2.0602 - val_mae: 1.2090 - val_mape: 77.7560 - val_mse: 1.9581
Epoch 67/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 1.2415 - mae: 0.3928 - mape: 1284.9755 - mse: 0.2452 - val_loss: 2.0520 - val_mae: 1.2108 - val_mape: 77.2698 - val_mse: 1.9670
Epoch 68/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.2281 - mae: 0.3893 - mape: 511.3613 - mse: 0.2868 - val_loss: 2.0271 - val_mae: 1.1956 - val_mape: 76.4326 - val_mse: 1.9181
Epoch 69/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1.2576 - mae: 0.4285 - mape: 591.0912 - mse: 0.3178 - val_loss: 2.0568 - val_mae: 1.2351 - val_mape: 79.4934 - val_mse: 2.0415
Epoch 70/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.2183 - mae: 0.3989 - mape: 286.2366 - mse: 0.2661 - val_loss: 2.0706 - val_mae: 1.2585 - val_mape: 82.4494 - val_mse: 2.1031
Epoch 71/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.2351 - mae: 0.4253 - mape: 544.8939 - mse: 0.3252 - val_loss: 2.0186 - val_mae: 1.2160 - val_mape: 79.2396 - val_mse: 1.9706
Epoch 72/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.2132 - mae: 0.4130 - mape: 285.4818 - mse: 0.2846 - val_loss: 1.9307 - val_mae: 1.1377 - val_mape: 73.7184 - val_mse: 1.7399
Epoch 73/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 1.1271 - mae: 0.3363 - mape: 305.5524 - mse: 0.2286 - val_loss: 1.8964 - val_mae: 1.1126 - val_mape: 73.0644 - val_mse: 1.6651
Epoch 74/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.2338 - mae: 0.4523 - mape: 321.2475 - mse: 0.3257 - val_loss: 1.8892 - val_mae: 1.1147 - val_mape: 72.7121 - val_mse: 1.6708
Epoch 75/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.2001 - mae: 0.4278 - mape: 380.3053 - mse: 0.3099 - val_loss: 1.9491 - val_mae: 1.1836 - val_mape: 78.3619 - val_mse: 1.8684
Epoch 76/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.1633 - mae: 0.4000 - mape: 800.0685 - mse: 0.2560 - val_loss: 1.9681 - val_mae: 1.2118 - val_mape: 79.7520 - val_mse: 1.9580
Epoch 77/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.1691 - mae: 0.4149 - mape: 230.0685 - mse: 0.2756 - val_loss: 1.9426 - val_mae: 1.1952 - val_mape: 78.4945 - val_mse: 1.9046
Epoch 78/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.1441 - mae: 0.3989 - mape: 241.6666 - mse: 0.2820 - val_loss: 1.9411 - val_mae: 1.2028 - val_mape: 79.0620 - val_mse: 1.9275
Epoch 79/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.1513 - mae: 0.4150 - mape: 377.3695 - mse: 0.2908 - val_loss: 1.9510 - val_mae: 1.2213 - val_mape: 79.4785 - val_mse: 1.9899
Epoch 80/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.0998 - mae: 0.3722 - mape: 259.6033 - mse: 0.2254 - val_loss: 1.9391 - val_mae: 1.2181 - val_mape: 78.3523 - val_mse: 1.9853
Epoch 81/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.0927 - mae: 0.3738 - mape: 298.6589 - mse: 0.2422 - val_loss: 1.9218 - val_mae: 1.2093 - val_mape: 77.7553 - val_mse: 1.9597
Epoch 82/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.1241 - mae: 0.4137 - mape: 2447.5684 - mse: 0.2718 - val_loss: 1.9005 - val_mae: 1.1965 - val_mape: 77.2819 - val_mse: 1.9167
Epoch 83/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.0373 - mae: 0.3354 - mape: 168.1020 - mse: 0.2104 - val_loss: 1.8862 - val_mae: 1.1907 - val_mape: 77.6600 - val_mse: 1.8914
Epoch 84/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.0940 - mae: 0.4006 - mape: 623.5433 - mse: 0.3077 - val_loss: 1.8683 - val_mae: 1.1812 - val_mape: 79.0475 - val_mse: 1.8457
Epoch 85/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.0716 - mae: 0.3866 - mape: 272.3069 - mse: 0.2863 - val_loss: 1.8599 - val_mae: 1.1811 - val_mape: 80.9425 - val_mse: 1.8323
Epoch 86/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.0659 - mae: 0.3892 - mape: 370.3392 - mse: 0.2701 - val_loss: 1.8317 - val_mae: 1.1611 - val_mape: 80.7479 - val_mse: 1.7683
Epoch 87/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.0240 - mae: 0.3554 - mape: 177.6192 - mse: 0.2399 - val_loss: 1.7899 - val_mae: 1.1274 - val_mape: 77.9907 - val_mse: 1.6767
Epoch 88/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.0180 - mae: 0.3574 - mape: 505.0492 - mse: 0.2077 - val_loss: 1.7268 - val_mae: 1.0722 - val_mape: 71.4915 - val_mse: 1.5448
Epoch 89/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.0022 - mae: 0.3495 - mape: 884.6813 - mse: 0.2070 - val_loss: 1.6864 - val_mae: 1.0397 - val_mape: 67.7111 - val_mse: 1.4675
Epoch 90/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 0.9813 - mae: 0.3365 - mape: 247.9773 - mse: 0.2242 - val_loss: 1.6609 - val_mae: 1.0221 - val_mape: 67.3761 - val_mse: 1.4172
Epoch 91/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 0.9965 - mae: 0.3595 - mape: 664.3140 - mse: 0.2194 - val_loss: 1.6540 - val_mae: 1.0229 - val_mape: 67.0381 - val_mse: 1.4182
Epoch 92/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 0.9878 - mae: 0.3585 - mape: 360.7329 - mse: 0.2352 - val_loss: 1.6436 - val_mae: 1.0201 - val_mape: 66.7861 - val_mse: 1.4107
Epoch 93/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 1.0258 - mae: 0.4040 - mape: 1280.2286 - mse: 0.2721 - val_loss: 1.6283 - val_mae: 1.0122 - val_mape: 65.8542 - val_mse: 1.3917
Epoch 94/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 0.9853 - mae: 0.3710 - mape: 357.0244 - mse: 0.2450 - val_loss: 1.6001 - val_mae: 0.9915 - val_mape: 65.2049 - val_mse: 1.3343
Epoch 95/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 0.9514 - mae: 0.3446 - mape: 320.6176 - mse: 0.2058 - val_loss: 1.5783 - val_mae: 0.9770 - val_mape: 64.9554 - val_mse: 1.2949
Epoch 96/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.9533 - mae: 0.3538 - mape: 332.3259 - mse: 0.2316 - val_loss: 1.5938 - val_mae: 0.9999 - val_mape: 65.4752 - val_mse: 1.3639
Epoch 97/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.9539 - mae: 0.3618 - mape: 587.0162 - mse: 0.2346 - val_loss: 1.6087 - val_mae: 1.0221 - val_mape: 66.6918 - val_mse: 1.4197
Epoch 98/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.9302 - mae: 0.3454 - mape: 362.6151 - mse: 0.1995 - val_loss: 1.5875 - val_mae: 1.0081 - val_mape: 66.2206 - val_mse: 1.3829
Epoch 99/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 0.9162 - mae: 0.3385 - mape: 232.3860 - mse: 0.2130 - val_loss: 1.5738 - val_mae: 1.0015 - val_mape: 66.0040 - val_mse: 1.3611
Epoch 100/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.9433 - mae: 0.3727 - mape: 274.7335 - mse: 0.2487 - val_loss: 1.5744 - val_mae: 1.0091 - val_mape: 66.6814 - val_mse: 1.3729
Epoch 101/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.9235 - mae: 0.3599 - mape: 344.7776 - mse: 0.2581 - val_loss: 1.6242 - val_mae: 1.0659 - val_mape: 70.3625 - val_mse: 1.5173
Epoch 102/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.8849 - mae: 0.3282 - mape: 386.0967 - mse: 0.2780 - val_loss: 1.6260 - val_mae: 1.0746 - val_mape: 71.8679 - val_mse: 1.5325
Epoch 103/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.8647 - mae: 0.3149 - mape: 434.5609 - mse: 0.1981 - val_loss: 1.6150 - val_mae: 1.0704 - val_mape: 71.5216 - val_mse: 1.5225
Epoch 104/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.8955 - mae: 0.3525 - mape: 1026.9122 - mse: 0.2243 - val_loss: 1.5866 - val_mae: 1.0487 - val_mape: 70.8426 - val_mse: 1.4623
Epoch 105/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.8839 - mae: 0.3477 - mape: 877.0259 - mse: 0.2212 - val_loss: 1.6182 - val_mae: 1.0871 - val_mape: 70.6320 - val_mse: 1.5832
Epoch 106/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.8616 - mae: 0.3321 - mape: 281.9697 - mse: 0.2066 - val_loss: 1.5902 - val_mae: 1.0658 - val_mape: 70.3903 - val_mse: 1.5196
Epoch 107/500

In [27]:
mae, rmse, nrmse, mape  = evaluate(y_true, y_pred)
print(f"MAE: {mae/60:.1f} min, RMSE: {rmse/60:.1f} min, NRMSE: {nrmse:.2f}, MAPE: {mape:.2f}%")


#  Przeliczenie na całkowity czas i ewaluacja 
print("\n Evaluating on total race time (not pace)...")

# Dystans w km
race_dist_km = test_meta["race_distance_m"].values / 1000.0
y_pred_time_sec = y_pred * race_dist_km
y_true_time_sec = y_true * race_dist_km

# Obliczenie metryk
mae_time, rmse_time, nrmse_time, mape_time = evaluate(y_true_time_sec, y_pred_time_sec)

print(f"MAE (czas): {mae_time/60:.1f} min")
print(f"RMSE (czas): {rmse_time/60:.1f} min")
print(f"NRMSE (czas): {nrmse_time:.2f}")
print(f"MAPE (czas): {mape_time:.2f}%")

# Przykładowe porównanie rzeczywistych i przewidywanych wyników
results_df = test_meta.copy()
results_df["y_true_pace_sec_per_km"] = y_true
results_df["y_pred_pace_sec_per_km"] = y_pred
results_df["y_true_time_min"] = y_true_time_sec/60
results_df["y_pred_time_min"] = y_pred_time_sec/60
results_df["error_time_min"] = (y_pred_time_sec - y_true_time_sec) / 60
results_df["error_pace_min"] = (y_pred - y_true) / 60
results_df["race_distance_km"] = results_df["race_distance_m"]/1000

print("\n Example results:")
results_df[["athlete", "lead_to_race_date", "race_distance_km","y_true_time_min", "y_pred_time_min", "error_time_min", "error_pace_min"]].head(50)

MAE: 0.3 min, RMSE: 0.5 min, NRMSE: 0.10, MAPE: 7.34%

 Evaluating on total race time (not pace)...
MAE (czas): 4.6 min
RMSE (czas): 11.8 min
NRMSE (czas): 0.23
MAPE (czas): 7.34%

 Example results:

,athlete,lead_to_race_date,race_distance_km,y_true_time_min,y_pred_time_min,error_time_min,error_pace_min
0,athlete_1,2025-05-11 13:49:39,10.07,34.916668,40.148045,5.231377,0.519501
1,athlete_1,2025-07-03 17:44:25,10.82,48.533331,48.525269,-0.008062,-0.000745
2,athlete_11,2024-04-13 19:31:21,10.09,49.016668,54.304013,5.287345,0.524018
3,athlete_11,2024-04-15 17:55:24,6.43,34.449999,34.179979,-0.270020,-0.041994
4,athlete_13,2024-12-24 07:43:19,8.03,41.966667,40.851122,-1.115545,-0.138922
5,athlete_13,2025-06-15 08:21:10,9.46,42.850002,43.017652,0.167651,0.017722
6,athlete_13,2025-07-01 10:19:35,7.92,34.583335,36.721519,2.138184,0.269973
7,athlete_13,2025-07-05 08:14:31,9.86,48.433333,44.487804,-3.945530,-0.400155
8,athlete_13,2025-07-28 08:08:44,14.20,68.166666,66.922758,-1.243908,-0.087599
9,athlete_13,2025-08-15 07:45:32,10.38,49.300000,47.371748,-1.928252,-0.185766
10,athlete_13,2025-09-05 16:39:20,11.41,56.399999,52.367291,-4.032708,-0.353436
11,athlete_13,2025-09-17 07:03:21,9.50,50.483333,49.281917,-1.201416,-0.126465
12,athlete_14,2025-10-01 16:08:45,5.34,29.049999,30.744320,1.694322,0.317289
13,athlete_14,2025-10-05 12:28:16,11.02,67.683336,63.940281,-3.743055,-0.339660
14,athlete_14,2025-10-09 18:15:44,5.06,28.200001,28.006290,-0.193711,-0.038283
15,athlete_14,2025-10-12 08:16:41,21.30,118.800000,128.259036,9.459036,0.444086
16,athlete_15,2024-05-19 11:04:28,6.13,28.683332,23.664569,-5.018763,-0.818722
17,athlete_15,2024-06-23 14:22:50,5.05,19.583333,21.719711,2.136378,0.423045
18,athlete_15,2024-08-07 16:28:06,4.85,20.000000,21.753844,1.753844,0.361617
19,athlete_15,2025-05-11 08:25:45,5.06,19.516667,21.642652,2.125985,0.420155
20,athlete_15,2025-08-30 15:00:54,3.81,13.883334,16.641259,2.757926,0.723865
21,athlete_15,2025-09-13 06:01:07,40.42,272.549995,345.603171,73.053176,1.807352
22,athlete_16,2024-04-13 19:31:21,10.09,49.016668,54.304013,5.287345,0.524018
23,athlete_16,2024-04-15 17:55:24,6.43,34.449999,34.179979,-0.270020,-0.041994
24,athlete_17,2025-06-19 10:03:39,10.01,47.366665,46.766619,-0.600046,-0.059945
25,athlete_17,2025-06-23 18:22:25,12.01,57.783336,56.424801,-1.358535,-0.113117
26,athlete_17,2025-07-28 21:07:25,8.50,46.366668,41.969576,-4.397092,-0.517305
27,athlete_17,2025-09-28 07:00:53,42.39,185.749993,228.571422,42.821429,1.010178
28,athlete_18,2025-10-19 08:00:11,42.36,205.450007,211.477379,6.027372,0.142289
29,athlete_2,2025-07-23 14:06:01,5.01,24.133332,23.123201,-1.010131,-0.201623
30,athlete_2,2025-07-26 11:29:42,10.02,42.399999,44.611409,2.211410,0.220700
31,athlete_2,2025-07-31 11:31:30,5.00,23.149999,22.600863,-0.549136,-0.109827
32,athlete_2,2025-08-02 14:46:43,5.01,22.766667,22.393689,-0.372978,-0.074447
33,athlete_2,2025-09-07 08:22:44,3.82,11.666667,13.983940,2.317273,0.606616
34,athlete_2,2025-09-11 15:55:07,4.93,22.383333,22.049669,-0.333664,-0.067680
35,athlete_2,2025-10-04 10:05:59,10.01,31.766667,32.431457,0.664790,0.066413
36,athlete_2,2025-10-12 08:00:05,21.20,69.016665,79.411645,10.394980,0.490329
37,athlete_3,2025-03-16 11:01:07,10.04,40.850000,42.010065,1.160066,0.115544
38,athlete_3,2025-03-30 09:01:36,21.22,94.683338,96.628300,1.944962,0.091657
39,athlete_3,2025-05-11 13:49:41,10.02,41.033334,42.556366,1.523032,0.151999
40,athlete_3,2025-06-14 20:00:24,21.20,91.566665,103.251919,11.685253,0.551191
41,athlete_3,2025-09-06 07:30:42,4.00,15.616667,19.831270,4.214604,1.053651
42,athlete_4,2025-04-05 10:30:25,4.21,16.500000,17.967804,1.467804,0.348647
43,athlete_5,2025-09-06 08:47:34,3.88,14.733333,16.788576,2.055243,0.529702
44,athlete_7,2025-08-20 16:39:30,5.11,22.016667,22.721725,0.705058,0.137976
45,athlete_7,2025-08-24 16:35:10,10.01,44.500002,46.133047,1.633045,0.163141
46,athlete_7,2025-09-15 15:37:05,10.00,44.899999,46.774612,1.874613,0.187461
47,athlete_7,2025-10-08 15:05:56,10.01,46.683335,46.255540,-0.427796,-0.042737
48,athlete_8,2023-03-20 21:03:07,5.56,26.233334,24.637594,-1.595740,-0.287004
49,athlete_8,2023-03-23 07:36:57,15.07,78.766665,67.962544,-10.804122,-0.716929